eCommerce/eCommerce/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace eCommerce.Models
{
    public class Product
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public decimal MSRP { get; set; }

        public virtual HashSet<ProductImage> ProductImages { get; set; }

        public Product()
        {
            this.ProductImages = new HashSet<ProductImage>();
        }

        public Product(int productId, string name, string desc, decimal price)
            : base()
        {
            this.ProductId = productId;
            this.Name = name;
            this.Description = desc;
            this.Price = price;
        }
    }
}

eCommerce/eCommerce/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace eCommerce.Controllers
{
    public class ProductsController : Controller
    {
        
        //this is our data context, think of it as the gateway to the database.  it's how we store and retrieve information from the database.
        private Models.ProductDataContext db = new Models.ProductDataContext();

        // GET: Products
        public ActionResult Index()
        {
            //return all products
            return View();
        }

        public ActionResult Details(int id)
        {
            //return just the one product the user wants to see
            return View();
        }
    }
}

eCommerce/eCommerce/Views/Products/Details.cshtml
@model eCommerce.Models.Product

@{
    ViewBag.Title = "Product Details";
}

<div class="row">
    <div class="col-md-8 product-details">
        <h2>Product Name</h2>
        <p>
            Product Description
        </p>
        <p>
            MSRP: <s>MSRP as currency</s>
            <br/>
            Our Price: <span class="price">Price as currency</span>
            
            @*if our price is less than the msrp price, display the following*@
            @if(model.Price < model.MSRP){
                @*Percent savings between our price and the MRSP*@
                <div>
                    var savings = Model.MSRP / (model.MSRP - model.Price);
                    You save <span class="price">@savings.ToString("P")</span>
                </div>
            }
        </p>
    </div>
    <div class="col-md-4 product-images">
        <img class="img-rounded main-image" src="@model.ProductImages.First().ImageUrl" alt="@model.ProductImages.First().Caption" />
        <div class="thumbnails text-center">
            @*for each product image for the product....*@
            @foreach(var image in model.ProductImages){
                <div class="thumbnail">
                    <img src="image.ImageUrl" alt="image.Caption" />
                </div>
            }
        </div>
    </div>
</div>
<div>
    @*link to go back to the main products list*@
    <a href="@Url.Action("Index", "Products")" class="btn btn-default">Back to Products</a>
</div>

eCommerce/eCommerce/Views/Products/Index.cshtml
@model eCommerce.Models.Product
@{
    ViewBag.Title = "Index";
}

<h2>Our Products</h2>

<div class="row">
    @foreach(var product in model){
        <div class="col-md-4 text-center product-listing">
            <a href="@Url.ActionLink("Details", "Prodcuts", new { id = model.ProductId})"> 
                <img src="@model.ProductImages.First().ImageUrl" alt="@model.ProductImages.First().Caption" class="img-thumbnail">
                <span class="name">
                    <strong>@model.Name</strong>
                    </span>
                <span class="price">@model.Price.ToString(c)</span>
                <a class="btn btn-default" href="@Url.ActionLink("Details", "Prodcuts", new { id = model.ProductId})">More Info</a>
            </a>
        </div>
    }
</div>